# Generated by Django 5.0.6 on 2024-05-21 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(max_length=9)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=80)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.account_chart')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
