# Generated by Django 5.0.6 on 2024-05-21 23:55

import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_chart',
            name='code',
            field=models.CharField(max_length=9, validators=[erp.validators.validate_is_digit]),
        ),
    ]
