# Generated by Django 5.0.6 on 2024-05-26 16:42

import django.db.models.deletion
import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_alter_account_chart_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, validators=[erp.validators.validate_is_digit])),
                ('name', models.CharField(max_length=50)),
                ('allocable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Chart_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, validators=[erp.validators.validate_is_digit])),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.chart_account'),
        ),
        migrations.AddField(
            model_name='chart_account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.chart_category'),
        ),
        migrations.DeleteModel(
            name='Account_chart',
        ),
    ]
