# Generated by Django 5.0.6 on 2024-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_chart_account_chart_category_alter_entry_account_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chart_account',
            constraint=models.UniqueConstraint(fields=('code', 'category'), name='unique_code'),
        ),
    ]
