# Generated by Django 5.0.6 on 2024-05-26 19:37

import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_entry_last_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_account',
            name='code',
            field=models.CharField(max_length=6, validators=[erp.validators.validate_is_digit]),
        ),
    ]
