# Generated by Django 5.0.6 on 2024-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_alter_chart_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('locked', True)), fields=('number',), name='unique_entry_number'),
        ),
    ]
