# Generated by Django 5.0.6 on 2024-05-23 11:04

import django.db.models.deletion
import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=11, unique=True, validators=[erp.validators.validate_is_digit])),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25, validators=[erp.validators.validate_is_digit])),
                ('creation_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('financial_year', models.CharField(max_length=4, unique=True, validators=[erp.validators.validate_is_digit])),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Company_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=11, unique=True, validators=[erp.validators.validate_is_digit])),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25, validators=[erp.validators.validate_is_digit])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_term', models.CharField(max_length=3, validators=[erp.validators.validate_is_digit])),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=11, unique=True, validators=[erp.validators.validate_is_digit])),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25, validators=[erp.validators.validate_is_digit])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_date', models.DateTimeField(auto_now=True)),
                ('starting_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.company')),
            ],
            options={
                'verbose_name_plural': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Client_current_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company_client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=2)),
                ('point_of_sell', models.CharField(max_length=5, validators=[erp.validators.validate_is_digit])),
                ('number', models.CharField(max_length=8, validators=[erp.validators.validate_is_digit])),
                ('description', models.TextField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('not_taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('VAT_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.payment_method')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.payment_term')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=2)),
                ('point_of_sell', models.CharField(max_length=5, validators=[erp.validators.validate_is_digit])),
                ('number', models.CharField(max_length=8, validators=[erp.validators.validate_is_digit])),
                ('description', models.TextField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('not_taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('VAT_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.payment_method')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.payment_term')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company_client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=2)),
                ('point_of_sell', models.CharField(max_length=5, validators=[erp.validators.validate_is_digit])),
                ('number', models.CharField(max_length=8, validators=[erp.validators.validate_is_digit])),
                ('description', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company_client')),
                ('related_invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.sale_invoice')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=2)),
                ('point_of_sell', models.CharField(max_length=5, validators=[erp.validators.validate_is_digit])),
                ('number', models.CharField(max_length=8, validators=[erp.validators.validate_is_digit])),
                ('description', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('related_invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.purchase_invoice')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_current_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='sale_invoice',
            constraint=models.UniqueConstraint(fields=('point_of_sell', 'number', 'type'), name='unique_sale_invoice_complete_number'),
        ),
        migrations.AddConstraint(
            model_name='sale_receipt',
            constraint=models.UniqueConstraint(fields=('point_of_sell', 'number', 'type'), name='unique_sale_receipt_complete_number'),
        ),
        migrations.AddConstraint(
            model_name='purchase_receipt',
            constraint=models.UniqueConstraint(fields=('sender', 'point_of_sell', 'number', 'type'), name='unique_purchase_receipt_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchase_invoice',
            constraint=models.UniqueConstraint(fields=('sender', 'point_of_sell', 'number', 'type'), name='unique_purchase_invoice_per_supplier'),
        ),
    ]
