# Generated by Django 5.0.6 on 2024-07-09 15:43

import django.db.models.deletion
import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_sale_receipt_sender_alter_sale_invoice_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_of_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_number', models.CharField(max_length=5, validators=[erp.validators.validate_is_digit])),
            ],
        ),
        migrations.AlterField(
            model_name='company_client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='pay_method',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_term',
            name='pay_term',
            field=models.CharField(max_length=3, unique=True, validators=[erp.validators.validate_is_digit]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sale_invoice',
            name='point_of_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.point_of_sell'),
        ),
        migrations.AlterField(
            model_name='sale_receipt',
            name='point_of_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.point_of_sell'),
        ),
    ]
