# Generated by Django 5.0.6 on 2024-07-09 16:04

import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_point_of_sell_alter_company_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_of_sell',
            name='pos_number',
            field=models.CharField(max_length=5, unique=True, validators=[erp.validators.validate_is_digit]),
        ),
    ]
