# Generated by Django 5.0.6 on 2024-07-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_point_of_sell_pos_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_of_sell',
            old_name='pos_number',
            new_name='pos_numbe',
        ),
    ]
