# Generated by Django 5.0.6 on 2024-07-14 11:45

import django.core.validators
import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_document_type_alter_purchase_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_type',
            name='type_description',
            field=models.CharField(default='description', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document_type',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[erp.validators.validate_is_digit]),
        ),
        migrations.AlterField(
            model_name='document_type',
            name='type',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='Invalid doc type', message='Insert letters only', regex='[a-zA-Z]')]),
        ),
    ]
