# Generated by Django 5.0.6 on 2024-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_remove_purchase_invoice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_receipt',
            name='description',
            field=models.CharField(default='Random stuff', max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_receipt',
            name='description',
            field=models.CharField(default='random stuff', max_length=280),
            preserve_default=False,
        ),
    ]
