# Generated by Django 5.0.6 on 2024-08-28 11:02

import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_purchase_invoice_vat_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_client',
            name='tax_number',
            field=models.CharField(error_messages={'unique': 'This tax number already exists.'}, max_length=11, unique=True, validators=[erp.validators.validate_is_digit]),
        ),
        migrations.AlterField(
            model_name='purchase_invoice',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase_receipt',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale_invoice',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale_receipt',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(error_messages={'unique': 'This tax number already exists.'}, max_length=11, unique=True, validators=[erp.validators.validate_is_digit]),
        ),
    ]
