# Generated by Django 5.0.6 on 2024-09-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_tax_number_alter_financialyear_year'),
        ('erp', '0015_rename_vat_amount_purchase_invoice_line_vat_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase_receipt',
            name='unique_purchase_receipt_per_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='sale_receipt',
            name='unique_sale_receipt_complete_number',
        ),
        migrations.RemoveField(
            model_name='purchase_receipt',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sale_receipt',
            name='type',
        ),
        migrations.AddConstraint(
            model_name='purchase_receipt',
            constraint=models.UniqueConstraint(fields=('sender', 'point_of_sell', 'number'), name='unique_purchase_receipt_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='sale_receipt',
            constraint=models.UniqueConstraint(fields=('point_of_sell', 'number'), name='unique_sale_receipt_complete_number'),
        ),
    ]
