# Generated by Django 5.0.6 on 2024-09-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_sale_invoice_collected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase_invoice',
            options={'ordering': ['-issue_date', 'sender', 'type', 'point_of_sell', 'number']},
        ),
        migrations.AlterModelOptions(
            name='purchase_receipt',
            options={'ordering': ['-issue_date', 'sender', 'point_of_sell', 'number']},
        ),
        migrations.AlterModelOptions(
            name='sale_invoice',
            options={'ordering': ['-issue_date', 'type', 'point_of_sell', 'number']},
        ),
        migrations.AlterModelOptions(
            name='sale_receipt',
            options={'ordering': ['-issue_date', 'point_of_sell', 'number']},
        ),
    ]
