# Generated by Django 5.0.6 on 2024-10-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_financialyear_options'),
        ('erp', '0018_alter_purchase_invoice_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_current_account',
            new_name='ClientCurrentAccount',
        ),
        migrations.RenameModel(
            old_name='Company_client',
            new_name='CompanyClient',
        ),
        migrations.RenameModel(
            old_name='Document_type',
            new_name='DocumentType',
        ),
        migrations.RenameModel(
            old_name='Payment_method',
            new_name='PaymentMethod',
        ),
        migrations.RenameModel(
            old_name='Payment_term',
            new_name='PaymentTerm',
        ),
        migrations.RenameModel(
            old_name='Point_of_sell',
            new_name='PointOfSell',
        ),
        migrations.RenameModel(
            old_name='Purchase_invoice',
            new_name='PurchaseInvoice',
        ),
        migrations.RenameModel(
            old_name='Purchase_invoice_line',
            new_name='PurchaseInvoiceLine',
        ),
        migrations.RenameModel(
            old_name='Purchase_receipt',
            new_name='PurchaseReceipt',
        ),
        migrations.RenameModel(
            old_name='Sale_receipt',
            new_name='SaleReceipt',
        ),
        migrations.RenameModel(
            old_name='Supplier_current_account',
            new_name='SupplierCurrentAccount',
        ),
        migrations.RenameModel(
            old_name='Sale_invoice',
            new_name='SaleInvoice',
        ),
        migrations.CreateModel(
            name='SaleInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=280)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('not_taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_invoice_lines', to='erp.saleinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Sale_invoice_line',
        ),
    ]
