# Generated by Django 5.0.6 on 2024-10-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_financialyear_options'),
        ('erp', '0019_rename_client_current_account_clientcurrentaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.supplier'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.supplier'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.companyclient'),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.companyclient'),
        ),
    ]
