# Generated by Django 5.0.6 on 2024-10-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_purchaseinvoice_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-issue_date', 'sender', 'type', 'point_of_sell', '-number']},
        ),
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['-issue_date', 'sender', 'point_of_sell', '-number']},
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'ordering': ['-issue_date', 'type', 'point_of_sell', '-number']},
        ),
        migrations.AlterModelOptions(
            name='salereceipt',
            options={'ordering': ['-issue_date', 'point_of_sell', '-number']},
        ),
    ]
