# Generated by Django 5.1.3 on 2025-01-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_alter_purchaseinvoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcurrentaccount',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.saleinvoice'),
        ),
        migrations.AddField(
            model_name='clientcurrentaccount',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.salereceipt'),
        ),
        migrations.AddField(
            model_name='suppliercurrentaccount',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='suppliercurrentaccount',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.purchasereceipt'),
        ),
        migrations.AlterField(
            model_name='clientcurrentaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientcurrentaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_account', to='erp.companyclient'),
        ),
        migrations.AlterField(
            model_name='clientcurrentaccount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='erp.companyclient'),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='erp.companyclient'),
        ),
        migrations.AlterField(
            model_name='suppliercurrentaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suppliercurrentaccount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suppliercurrentaccount',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_account', to='erp.supplier'),
        ),
    ]
