# Generated by Django 5.1.3 on 2025-02-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_clientcurrentaccount_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercurrentaccount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_account', to='erp.supplier'),
        ),
    ]
