# Generated by Django 5.1.3 on 2025-02-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_alter_suppliercurrentaccount_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='type_description',
            new_name='description',
        ),
    ]
