# Generated by Django 5.0.6 on 2024-06-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_financial_year_financialyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
