# Generated by Django 5.0.6 on 2024-06-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_financialyear_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='financialyear',
            constraint=models.UniqueConstraint(condition=models.Q(('current', True)), fields=('current',), name='unique_true_current_year'),
        ),
    ]
