# Generated by Django 5.0.6 on 2024-08-27 20:52

import company.validators
import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(error_messages={'unique': 'This tax number already exists.'}, max_length=11, unique=True, validators=[erp.validators.validate_is_digit]),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='year',
            field=models.CharField(max_length=4, unique=True, validators=[erp.validators.validate_is_digit, company.validators.validate_valid_year]),
        ),
    ]
