# Generated by Django 5.0.6 on 2024-09-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_tax_number_alter_financialyear_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialyear',
            options={'ordering': ['current', '-year']},
        ),
    ]
