# Generated by Django 5.0.6 on 2024-09-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_financialyear_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialyear',
            options={'ordering': ['-current', '-year']},
        ),
    ]
