# Generated by Django 5.1.3 on 2025-01-16 23:27

import company.validators
import erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_financialyear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='year',
            field=models.CharField(error_messages={'unique': 'The year already exists.'}, max_length=4, unique=True, validators=[erp.validators.validate_is_digit, company.validators.validate_in_creation_year]),
        ),
    ]
